use foundation::span::Span;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenKind {
    Identifier,
    Integer,
    Float,
    String,
    Char,
    Bool,
    Null,
    If,
    Else,
    While,
    Break,
    Continue,
    For,
    Fn,
    Return,
    Struct,
    Impl,
    Trait,
    SelfKw,
    SelfType,
    TypeName,
    Plus,
    PlusPlus,
    PlusAssign,
    Minus,
    MinusMinus,
    Arrow,
    MinusAssign,
    Star,
    StarAssign,
    DoubleStar,
    DoubleStarAssign,
    Slash,
    SlashAssign,
    Percent,
    PercentAssign,
    Bang,
    Tilde,
    Ampersand,
    AmpersandAssign,
    Pipe,
    PipeAssign,
    Caret,
    CaretAssign,
    ShiftLeft,
    ShiftLeftAssign,
    ShiftRight,
    ShiftRightAssign,
    AndAnd,
    OrOr,
    EqualEqual,
    BangEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Comma,
    Dot,
    Semicolon,
    Colon,
    DoubleColon,
    Assign,
    InferAssign,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: String,
    pub span: Span,
}
